Make list of plots -> subplots
Ribbit-Network/ribbit-network-dashboard pull request #52
Opened 2021-10-08 22:52 UTC by sriki18

Use Plotly's `add_trace` instead of Plotly express to plot the timeseries while converting it from a list of plots to one figure with subplots. Plots now share X axis, so zooming in one will also zoom in the others. Fixes #30

2021-10-10 01:44 UTC, sriki18 commented
@keenanjohnson not sure if you had a look!

2021-11-22 20:14 UTC, spestana commented
@sriki18 @keenanjohnson What do you think about adding a second y-axis to the temperature and pressure plots, so we can see the measurements in different units? 

So we would retain the current "scientific/metric" units on the left, then add another axis with alternate units on the right (old-fashioned US/Imperial units).

- **Temperature**: degrees C on the left, and degrees F on the right
- **Pressure**: mbar on the left, and "inches of Hg" on the right

(@keenanjohnson I can help review this PR if I had the permissions to assign myself as reviewer)

2021-11-22 23:11 UTC, keenanjohnson commented
Oh sure thing @spestana ! I can add you! Seems like this PR has gone a bit stale if you want to help push it along :)

2021-11-23 16:53 UTC, sriki18 commented
I can do that, should it be a branch once this branch has been merged? @keenanjohnson @spestana

2021-11-23 19:30 UTC, keenanjohnson commented
@sriki18 can you see my comment in the review previously about the read-ability?

2021-11-23 21:29 UTC, spestana commented on app.py
> +        fig.add_scatter(x=sensor_data["Time"], y=sensor_data[col], mode="lines", line=go.scatter.Line(color="gray"), showlegend=False, row=ind+1, col=1)
Can you change this to
`fig.add_scatter(x=sensor_data["Time"], y=sensor_data[col], mode="lines", line=go.scatter.Line(color="black"), showlegend=False, row=ind+1, col=1, hovertemplate="Time: %{x}<br>%{text}: %{y:.2f}<extra></extra>", text=[col]*len(sensor_data[col]))`

This adds the hovertemplate to match our existing hover features.

2021-11-23 21:31 UTC, spestana requested changes
@sriki18  See my comment on line 228 about the hovertemplate text to match our existing hover info.

2021-11-24 17:20 UTC, sriki18 commented
@spestana done. Have a look!

2021-11-24 18:05 UTC, spestana approved these changes
looks good!

2021-11-24 18:06 UTC, merged